const products = [
  {
    '_id': '1',
    'name': 'Wood and Cloth sofa',
    'img1': 'https://htmldemo.hasthemes.com/lezada/lezada/assets/images/products/furniture-2-2-600x800.jpg',
    'img2': 'https://htmldemo.hasthemes.com/lezada/lezada/assets/images/products/furniture-2-1-600x800.jpg',
    'description':
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    'brand': 'Apple',
    'category': 'Electronics',
    'old_price': 89.99,
    'new_price': 80.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Wood and Cloth sofa',
    'img1': 'https://htmldemo.hasthemes.com/lezada/lezada/assets/images/products/furniture-2-2-600x800.jpg',
    'img2': 'https://htmldemo.hasthemes.com/lezada/lezada/assets/images/products/furniture-2-1-600x800.jpg',
    'description':
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    'brand': 'Apple',
    'category': 'Electronics',
    'old_price': 89.99,
    'new_price': 80.99,
    'countInStock': 0,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '3',
    'name': 'Wood and Cloth sofa',
    'img1': 'https://htmldemo.hasthemes.com/lezada/lezada/assets/images/products/furniture-2-2-600x800.jpg',
    'img2': 'https://htmldemo.hasthemes.com/lezada/lezada/assets/images/products/furniture-2-1-600x800.jpg',
    'description':
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    'brand': 'Apple',
    'category': 'Electronics',
    'old_price': 89.99,
    'new_price': 80.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'Wood and Cloth sofa',
    'img1': 'https://htmldemo.hasthemes.com/lezada/lezada/assets/images/products/furniture-2-2-600x800.jpg',
    'img2': 'https://htmldemo.hasthemes.com/lezada/lezada/assets/images/products/furniture-2-1-600x800.jpg',
    'description':
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    'brand': 'Apple',
    'category': 'Electronics',
    'old_price': 89.99,
    'new_price': 80.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '5',
    'name': 'Wood and Cloth sofa',
    'img1': 'https://htmldemo.hasthemes.com/lezada/lezada/assets/images/products/furniture-2-2-600x800.jpg',
    'img2': 'https://htmldemo.hasthemes.com/lezada/lezada/assets/images/products/furniture-2-1-600x800.jpg',
    'description':
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    'brand': 'Apple',
    'category': 'Electronics',
    'old_price': 89.99,
    'new_price': 80.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '6',
    'name': 'Wood and Cloth sofa',
    'img1': 'https://htmldemo.hasthemes.com/lezada/lezada/assets/images/products/furniture-2-2-600x800.jpg',
    'img2': 'https://htmldemo.hasthemes.com/lezada/lezada/assets/images/products/furniture-2-1-600x800.jpg',
    'description':
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    'brand': 'Apple',
    'category': 'Electronics',
    'old_price': 89.99,
    'new_price': 80.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '7',
    'name': 'Wood and Cloth sofa',
    'img1': 'https://htmldemo.hasthemes.com/lezada/lezada/assets/images/products/furniture-2-2-600x800.jpg',
    'img2': 'https://htmldemo.hasthemes.com/lezada/lezada/assets/images/products/furniture-2-1-600x800.jpg',
    'description':
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    'brand': 'Apple',
    'category': 'Electronics',
    'old_price': 89.99,
    'new_price': 80.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
]


export default products